version: '{build}'
os: Windows Server 2012
clone_depth: 10
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%;%comspec%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - cmd: mvn clean package -q --batch-mode -DskipTests -DfinalName=sharpen
test_script:
  - cmd: mvn -DfinalName=sharpen test -q
after_test:
  - cmd: mvn install -q -Pqulice -DskipTests -DfinalName=sharpen > code_quality_report.txt || exit /B 0
artifacts: 
  - path: src\target\sharpen-jar-with-dependencies.jar
    name: sharpen-with-dependencies

  - path: code_quality_report.txt
    name: Code quality messages
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2


